name: Build and Push (getsimple-cms CVE-2022-41544)

on:
  push:
    branches: [ main ]
    paths:
      - 'getsimple-cms/CVE-2022-41544/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'getsimple-cms/CVE-2022-41544/**'

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read Docker Image Identifiers
        id: read-docker-image-identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }}/getsimple-cms-cve-2022-41544 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}
          tags: |
            type=sha
            type=raw,value=3.3.16,enable={{is_default_branch}}
      - name: Environment
        run: printenv
      - name: Check Limits
        run: ulimit -a
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./getsimple-cms/CVE-2022-41544
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
